baseURL = 'https://obsidian-pub.pages.dev/'
languageCode = 'en-us'
title = 'Hugo Site!'
#theme = 'ananke'
theme = 'PaperMod'
followSymlinks = true


[[menu.main]]
    identifier = "categories"
    name = "Categories"      # 메뉴에 표시될 이름
    url = "/categories/"     # 카테고리 전체 목록 페이지 주소
    weight = 10

    identifier: "tags"
    name: "tags"
    url: "/tags/"
    weight: 20


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

#[params]
#ShowReadingTime = true
#  
#[params.sidebar]
#enable = true
#showReCentPosts = true
#showTaxonomy = true
#ShowTaxonomyMaxNum = 10  # 최대 10개 표시